debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    p6spy: info
    com.takealook.projectboard: debug
    org.springframework.web.servlet: debug

spring:
  datasource:
    url: ENC(78hlc2cJdAw5Lgw37j8w7zuWlSWXSq5vaQfuds3n5b6PShL6oOabvBa1vPkDOF8Cs+hr8vf7EeAdBRamWIC89/WMGNJTe/sVVJHI4inNLlaPS4E4yyhEsjF3BnBhvSIayTqOw736Z7t3HyxHRqjBdQ==)
    username: ENC(4aGcJI+ATyrHsG5kkl3s9So5RmpC2a5jW6EQaQoV3AM=)
    password: ENC(rv6ZLH9Ufopo7EgkTEzPSwAbu9357Z/0vgbNmBvdrso=)
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true # data.sql 로드
    hibernate:
      ddl-auto: create # none create
    properties:
      hibernate.default_batch_fetch_size: 100
  sql:
    init:
      mode: always # embedded 임베디드 DB의 경우만 동작, never 동작안함

decorator:
  datasource:
    p6spy:
      enable-logging: true
      logging: slf4j
      multiline: true
