debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    p6spy: info
    com.takealook.projectboard: debug
    org.springframework.web.servlet: debug

spring:
  datasource:
    url: ENC(j/dMi1B25PwM1qxtt+g2jTBfnw31ev/WM9Wgf6G3cac7SJe9Lcp7f7J5Y6I9K53WpZT+uNMo1RWJAOBzXajsKER/kbZ1o27y4GvcRUzs9WNzAuwTtPtIFVuqpYmuzkMn1cL41dRnGTLttyOVg1/rFA==)
    username: ENC(HRDWRmddnenOOOlfd81zblZd5Eml2fqyTdeLir3bS/o=)
    password: ENC(I4HXNaqRsiHhiu7pmddheEddzLt3Y3DoAuR8P8/8Fjg=)
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true # data.sql 로드
    hibernate:
      ddl-auto: create # none create
    properties:
      hibernate.default_batch_fetch_size: 100
  sql:
    init:
      mode: always # embedded 임베디드 DB의 경우만 동작, never 동작안함

decorator:
  datasource:
    p6spy:
      enable-logging: true
      logging: slf4j
      multiline: true
