server:
  port: 8080

debug: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  profiles:
    active: dev
  datasource:
    url: ENC(j/dMi1B25PwM1qxtt+g2jTBfnw31ev/WM9Wgf6G3cac7SJe9Lcp7f7J5Y6I9K53WpZT+uNMo1RWJAOBzXajsKER/kbZ1o27y4GvcRUzs9WNzAuwTtPtIFVuqpYmuzkMn1cL41dRnGTLttyOVg1/rFA==)
    username: ENC(HRDWRmddnenOOOlfd81zblZd5Eml2fqyTdeLir3bS/o=)
    password: ENC(I4HXNaqRsiHhiu7pmddheEddzLt3Y3DoAuR8P8/8Fjg=)
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none # none create
    properties:
      hibernate.default_batch_fetch_size: 100
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  h2:
    console:
      enabled: false
  thymeleaf3:
    decoupled-logic: true

logging:
  level:
    p6spy: info
    com.takealook.projectboard: debug
    org.springframework.web.servlet: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true
      logging: slf4j
      multiline: true

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true # data.sql 로드
    hibernate:
      ddl-auto: create # none create
  sql:
    init:
      mode: always # embedded 임베디드 DB의 경우만 동작, never 동작안함

